version: "3.9"

services:
  fastapi_app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - .env 
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  processor:
    build: .
    container_name: enrollment_processor
    depends_on:
      - mongodb
    volumes:
      - ./app:/app
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    command: ["python", "services/enrollment_processor.py"]

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: